// Code generated by mockery v1.0.0. DO NOT EDIT.

package redsyncx

import mock "github.com/stretchr/testify/mock"

// mockExtendableMutex is an autogenerated mock type for the extendableMutex type
type mockExtendableMutex struct {
	mock.Mock
}

// Extend provides a mock function with given fields:
func (_m *mockExtendableMutex) Extend() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Lock provides a mock function with given fields:
func (_m *mockExtendableMutex) Lock() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Unlock provides a mock function with given fields:
func (_m *mockExtendableMutex) Unlock() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
